services:
  bg-trail-db:
    container_name: bg-trail-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "bg-trail-mongodb:/data/db"

  bg-trail-backend:
    container_name: bg-trail-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - "./backend:/app"
      - "/app/node_modules"

  bg-trail-frontend:
    container_name: bg-trail-frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"

volumes:
  bg-trail-mongodb:
